name: Create pipeline-basic image

on: workflow_dispatch

jobs:
  build-basic-pipeline:
    runs-on: ubuntu-latest
    container:  hashicorp/packer:1.11
    env:
      DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
      DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Packer Version
        run: |
          packer version

      - name: Create zepben/pipeline-basic
        run: |
          apk add docker tar
          mkdir /build
          export PACKER_CONFIG_DIR=/build
          cd pipelines/basic/
          packer init basic.pkr.hcl
          packer validate basic.pkr.hcl
          packer build -on-error=abort -var dockerhub_user=$DOCKER_HUB_USER -var dockerhub_pw=$DOCKER_HUB_ACCESS_TOKEN basic.pkr.hcl
        shell: bash

