name: Create Docusaurus pipleine

on:
  workflow_dispatch:
    inputs:
      push_image:
        description: If the image should be pushed
        type: boolean
        default: false

jobs:
  checks:
    runs-on: ubuntu-latest
    container:  zepben/pipeline-docusaurus
    outputs:
      store_modules: ${{ steps.store.modules }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Work around git permission issue
        run: |
          dname=$(echo ${{github.repository}} | cut -d'/' -f2)
          git config --global --add safe.directory /__w/$dname/$dname
        shell: sh

      - name: Login to NPM
        run: |
          rm -rf ~/.npmrc
          echo "@zepben:registry=${{ secrets.NEXUS_NPM_REPO }}" >> ~/.npmrc
          echo "//nexus.z.zepben.cloud/repository/zepben-npm/:_authToken=${{ secrets.CI_NPM_TOKEN }}" >> ~/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.CI_GITHUB_TOKEN }}" >> ~/.npmrc

      - name: Check that build works
        id: build
        run: |
          # use templates from the current branch
          cd pipelines/Docusaurus/docs
          make

      - name: Detect package-lock change
        id: store
        if: steps.build.outcome == 'success'
        run: | 
          files=$(git diff "origin/${{ github.event.repository.default_branch }}" --name-only | paste -s -d,) 
          echo $files
          # Check if package-lock.json is changed
          if [[ "$files" =~ "package-lock.json" ]]; then
            echo "package-lock changed, save new modules"
            echo "modules=yes" >> "${GITHUB_OUTPUT}"
            echo "modules=yes" >> "${GITHUB_ENV}"
          fi
        shell: bash

      # only update node_modules in the container if there's a change
      - name: Zip node_modules
        id: zip
        if: ${{ env.modules }} == 'yes'
        run: |
          cd pipelines/Docusaurus/docs/site-config
          zip -r node_modules.zip node_modules/ 
        shell: sh

      - name: Upload node_modules
        uses: actions/upload-artifact@v4
        if: steps.zip.outcome == 'success'
        with:
          name: node_modules.zip
          path: pipelines/Docusaurus/docs/site-config/node_modules.zip
          if-no-files-found: error


  parse-inputs:
    needs: [checks]
    runs-on: ubuntu-latest
    container:  zepben/pipeline-basic
    outputs:
      git_tag: ${{ steps.tags.outputs.git_tag }}
    steps:

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Work around git permission issue
        run: |
          dname=$(echo ${{github.repository}} | cut -d'/' -f2)
          git config --global --add safe.directory /__w/$dname/$dname
        shell: sh

      - name: Delete release branch
        run: |
          # If the `release` branch already exists, remove it
          # disable error failing
          set +e 
          res=$(git push origin -d release)
          if [ $? != 0 ]; then
            echo "> [!NOTE] " >> "$GITHUB_STEP_SUMMARY"
            echo "> :white_check_mark: Error while deleting 'release' branch in *parse-inputs* step, but that's probably OK. If nothing else failed, you're good." >> "$GITHUB_STEP_SUMMARY"
          fi
        continue-on-error: true 
        shell: bash 

      - name: Create release branch
        run: |
          git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
          git fetch -v origin
          git checkout -b release
        shell: bash

      - name: Figure out the tag for the build
        id: tags
        shell: bash
        run: |
          version=$(cat changelog.md | grep UNRELE | grep -o "[0-9]\+\.[0-9]\+\.[0-9]\+")
          source /scripts/common.sh
          check_tag_exists "${version}"

          if [ ${GITHUB_REF_NAME} == "main" ]; then
            echo "git_tag=${version}" >> "${GITHUB_OUTPUT}"
          else
            echo "git_tag=test-${GITHUB_REF_NAME}" >> "${GITHUB_OUTPUT}"
          fi

      - name: Update changelog and commit release branch
        shell: bash
        if: ${{ github.ref_name == 'main' }}
        run: |
          source /scripts/common.sh
          sed -i "s/UNRELEASED/$(date +'%Y-%m-%d')/g" changelog.md
          # Update changelog version
          incr_version minor ${{ steps.tags.outputs.git_tag }}
          release_notes_template="### Breaking Changes\n* None.\n\n### New Features\n* None.\n\n### Enhancements\n* None.\n\n### Fixes\n* None.\n\n### Notes\n* None.\n"
          sed -i "/^# .*/a ## [${new_version}] - UNRELEASED\n$release_notes_template" changelog.md

          stage_file changelog.md

          # Reset new_version to the unreleased yet tag
          new_version=${{ steps.tags.outputs.git_tag }}
          # Push release branch to repo
          commit_finalize_version

  build-docusaurus-pipeline:
    runs-on: ubuntu-latest
    needs: [checks, parse-inputs]
    env:
      DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
      DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      # TODO: restore node_modules if there was a change in package-lock.js
      - name: Download modules
        if: ${{ needs.checks.store_modules == 'yes' }}
        uses: actions/download-artifact@v4
        with:
          name: node_modules.zip
          path: pipelines/Docusaurus/templates/node_modules.zip
        continue-on-error: false

      - name: Unzip modules
        run: |
          cd pipelines/Docusaurus/templates/
          unzip node_modules.zip
          rm -rf node_modules.zip

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Container Registry
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ env.DOCKER_HUB_USER }}
          password: ${{ env.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Get SHAs
        id: sha
        run: |
          SHORT_REF=$(git rev-parse --short HEAD)
          echo "short_ref=$SHORT_REF" >> $GITHUB_OUTPUT

      # Priority sorting determines the tag used in the OCI label
      # The current order preferences the version, then commit, then any special tags
      # We always push a commit based tag
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: zepben/pipeline-docusaurus
          labels: |
            org.opencontainers.image.vendor=Zepben
            org.opencontainers.image.version=${{ needs.parse-inputs.outputs.git_tag }}
          tags: |
            type=raw,value=sha-${{ steps.sha.outputs.short_ref }},priority=200
            type=raw,value=${{ needs.parse-inputs.outputs.git_tag }},priority=900
            type=raw,value=latest,enable=${{ github.ref_name == 'main' }},priority=100

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "./pipelines/Docusaurus"
          push: ${{ inputs.push_image }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  finalise-version:
    runs-on: ubuntu-latest
    if: ${{ github.ref_name == 'main' }}
    container: zepben/pipeline-basic
    needs: [build-docusaurus-pipeline, parse-inputs]
    env:
      GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ env.GITHUB_TOKEN }}

      - name: Work around git permission issue
        run: |
          dname=$(echo ${{github.repository}} | cut -d'/' -f2)
          git config --global --add safe.directory /__w/$dname/$dname
        shell: sh

      - name: Merge and tag
        shell: bash
        id: tag
        run: |
          # Merge and tag, and delete release branch
          git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
          git fetch --all
          git branch -a
          git merge origin/release
          git push origin ${GITHUB_REF/refs\/heads\//}
          git tag "${{ needs.parse-inputs.outputs.git_tag }}"
          git push --tags
          git push origin -d release
