name: Create amazoncorretto image

on: workflow_dispatch

jobs:
  build_java_amazoncorretto:
    runs-on: ubuntu-latest
    container:  hashicorp/packer:1.11
    env:
      DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
      DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Create zepben/pipeline-java-amazoncorretto
        run: |
          apk add docker tar
          mkdir /build
          export PACKER_CONFIG_DIR=/build
          cd pipelines/Java/
          packer build -on-error=abort -var dockerhub_user=$DOCKER_HUB_USER -var dockerhub_pw=$DOCKER_HUB_ACCESS_TOKEN amazoncorretto-config.pkr.hcl
        shell: bash
