name: Create js image

on: workflow_dispatch

jobs:
  build_basic:
    runs-on: ubuntu-latest
    container:  hashicorp/packer:1.9
    env:
      DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
      DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Create zepben/pipeline-node
        run: |
          apk add docker
          mkdir /build
          export PACKER_CONFIG_DIR=/build
          cd pipelines/JavaScript/
          packer build -var dockerhub_user=$DOCKER_HUB_USER -var dockerhub_pw=$DOCKER_HUB_ACCESS_TOKEN config.json
        shell: bash
